### ISSUE TITLE
Together model not found

### ISSUE THREAD

**Issue by wjwei-handsome** [evo-design/evo#14]
Hi!

Excellent work and papers!

But when I tried to use the together api, following the example in the README documentation, I found such an error.
```
openai.NotFoundError: Error code: 404 - {'error': {'message': 'Unable to access model togethercomputer/evo-1-131k-base. Please visit https://api.together.xyz to see the list of supported models or contact the owner to request access.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
```

message Information :

```
chat_completion = client.chat.completions.create(
    messages=[
        {"role": "system", "content": ""},
        {
            "role": "user",
            "content": "ACGT",  # Prompt the model with a sequence.
        },
    ],
    model="togethercomputer/evo-1-131k-base",
    max_tokens=128,  # Sample some number of new tokens.
    logprobs=True,
)
```

Is there something missing?

Thanks!

**Comment by JinyuanSun** [comment]
Same error. And I didn't found `evo-1-131k-base` in the model list at `https://api.together.xyz/models`.

**Comment by Zymrael** [comment]
Together API will be live tomorrow!

**Comment by JinyuanSun** [comment]
will the model on together allows finetuning？

**Comment by wjwei-handsome** [comment]
> Together API will be live tomorrow!

Hi @Zymrael 宁致远，Thanks, I have seen it!

**Comment by wjwei-handsome** [comment]
btw, the together link in arc Institute [blog page](https://arcinstitute.org/news/blog/evo) is wrong:

https://api.together.xyz/playground/genomics/togethercomputer/evo-1-131k-base 
--->>> 
https://api.together.xyz/playground/language/togethercomputer/evo-1-131k-base

**Comment by Zymrael** [comment]
The links provided by @wjwei-handsome are correct. The model is up on the API, we'll announce it tomorrow with examples.

**Comment by JinyuanSun** [comment]
Hi, I found the API might be down again. The error I got is: 
```
 Error code: 400 - {'error': {'message': 'Unable to access non-serverless model togethercomputer/evo-1-131k-base. Please visit https://api.together.ai/models/togethercomputer/evo-1-131k-base to create and start a new dedicated endpoint for the model.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_available'}}
 ```
