### ISSUE TITLE
How can I use this tool to solve the practical biological problem of predicting transcription factor target sequences in actual biology?

### ISSUE THREAD

**Issue by lizhebio** [evo-design/evo#16]

**Comment by JinyuanSun** [comment]
1. You need a dataset, where known TFs and targets aer paired.
2. Finetune this model.

**Comment by lizhebio** [comment]
> 2\. Finetune this model.

Is there a demo about how to fine-tune?

**Comment by JinyuanSun** [comment]
A fine-tuning example in pull request #17
