### ISSUE TITLE
Inquiry Regarding Local Model Usage and Importing Model Files

### ISSUE THREAD

**Issue by yyly6** [evo-design/evo#22]
Due to connectivity issues with my server, I am unable to directly access the HuggingFace.  As a result, I encountered difficulties when attempting to import models using the standard methods, such as Evo('evo-1-131k-base'). Even when attempting to import models using a local path, I have not been successful.

Could you please provide guidance on how to successfully import them into a local environment? 

Thank you very much for your attention to this matter. I am eager to receive your guidance and assistance.

**Comment by Zymrael** [comment]
Did you clone the HF model repo? I'd recommend posting this in the `transformers` library issue tracker.

**Comment by Licko0909** [comment]
I also encountered the same issue; this can help you solve it.

`HF_ENDPOINT=https://hf-mirror.com python your_script.py`

![image](https://github.com/evo-design/evo/assets/27897166/69144e42-33db-46e2-af85-a1ee66bca8ef)
