### ISSUE TITLE
AssertionError: rotary_emb is not installed

### ISSUE THREAD

**Issue by bioone** [evo-design/evo#23]
i try the fllow code：
`from transformers import AutoConfig, AutoModelForCausalLM

model_name = 'togethercomputer/evo-1-8k-base'

model_config = AutoConfig.from_pretrained(model_name, trust_remote_code=True)
model_config.use_cache = True

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    config=model_config,
    trust_remote_code=True,
)`

raise error ：AssertionError: rotary_emb is not installed

however，the rotary_emb v0,1 installed，flash attentation also installed

**Comment by exnx** [comment]
can you share more info / stack trace?  It might be the flash attention version.

**Comment by xmz111** [comment]
#10

**Comment by dorukcakmakci** [comment]
I believe the source of this error is this [line](https://github.com/Dao-AILab/flash-attention/blob/main/flash_attn/modules/mha.py#L31C5-L31C57) in flash-attention codebase. In my case, the import statement encapsulated in the try-except block failed with the following error: `ModuleNotFoundError: No module named 'triton'`. Installing `triton` fixed the problem.

**Comment by sokrypton** [comment]
I'm having same issue on Google Colab, using A100.

Any fix?

**Comment by brianhie** [comment]
Problem looks to be caused by a try except in flash attention not propagating the ModuleNotFoundError when triton is not installed. We've added triton to requirements.txt in https://github.com/evo-design/evo/pull/81
