### ISSUE TITLE
Prompt for virus and plasmid generation

### ISSUE THREAD

**Issue by apcamargo** [evo-design/evo#37]
The example notebook show the utilization of a Greengenes-style lineage as a prompt for generation. However, it does not address the process of prompting for non-chromosomal sequences. For viruses, was the ICTV taxonomy from IMG/VR used during training? Additionally, concerning plasmids, if their host lineage was utilized, how can I direct Evo to generate a plasmid?

**Comment by brianhie** [comment]
>For viruses, was the ICTV taxonomy from IMG/VR used during training?

This is correct!

>Additionally, concerning plasmids, if their host lineage was utilized, how can I direct Evo to generate a plasmid?

During the finetuning phase, there was no species level prompt prepended to the plasmids.
