### ISSUE TITLE
OSError: togethercomputer/evo-1-131k-base does not appear to have a file named pytorch_model.bin, tf_model.h5, model.ckpt or flax_model.msgpack.

### ISSUE THREAD

**Issue by jingliezhou** [evo-design/evo#39]
Hi,

I just run the example command:
```
from evo import Evo
import torch

device = 'cuda:1'

evo_model = Evo('evo-1-131k-base')
model, tokenizer = evo_model.model, evo_model.tokenizer
model.to(device)
model.eval()

sequence = 'ACGT'
input_ids = torch.tensor(
    tokenizer.tokenize(sequence),
    dtype=torch.int,
).to(device).unsqueeze(0)
logits, _ = model(input_ids) # (batch, length, vocab)

print('Logits: ', logits)
print('Shape (batch, length, vocab): ', logits.shape)
```

But it show the error as below, even if I directly the huggingface version. Does anyone know what's the problem?
`OSError: togethercomputer/evo-1-131k-base does not appear to have a file named pytorch_model.bin, tf_model.h5, model.ckpt or flax_model.msgpack.`

Thanks,
Jinglie

**Comment by davidkell** [comment]
I had this issue and updating to latest version of transformers fixed it for me

**Comment by jingliezhou** [comment]
> I had this issue and updating to latest version of transformers fixed it for me

Thank you!
