### ISSUE TITLE
Questions about the performance of evo

### ISSUE THREAD

**Issue by HelloWorldLTY** [evo-design/evo#40]
Given the example "ACGT" as prompt, it seems that the output data from 8k-base model are strange:

![image](https://github.com/evo-design/evo/assets/43333475/100a51ad-f558-42b6-98d7-eff34b0da796)

Is it possible to discover such a DNA sequence in the real world? I assume there are no sequence with so many Ts like this. Thanks.

**Comment by exnx** [comment]
Try playing around with the settings to control the quality, temperature, top_k etc
