### ISSUE TITLE
131k base seems to output non-DNA characters

### ISSUE THREAD

**Issue by cosmicBboy** [evo-design/evo#56]
Might be missing some context, but the 131k base model seems to output unexpected characters

<img width="1241" alt="image" src="https://github.com/evo-design/evo/assets/2816689/fe0c7b67-e7d5-4e64-a5e6-4014e5e7658d">

The 8k base model looks okay:
<img width="1250" alt="image" src="https://github.com/evo-design/evo/assets/2816689/92583bf6-10d4-4909-bbdc-48e66223c569">

**Comment by brianhie** [comment]
What sampling parameters (temperature, etc.) are you using?

**Comment by cosmicBboy** [comment]
The default 0.7 setting. It doesn't seem to change if I set it to `0` or `2`
<img width="1714" alt="image" src="https://github.com/evo-design/evo/assets/2816689/18e3fa9a-8382-4c51-b00e-da4ecd870817">

<img width="1708" alt="image" src="https://github.com/evo-design/evo/assets/2816689/47c5191c-bd6f-4dc8-908f-197e103ffe75">

**Comment by Zymrael** [comment]
There is a problem with Evo 131k on the Together API, for now please use the HF version.

**Comment by cosmicBboy** [comment]
cool, I'll give that a try
